
project_id = "siuqvhscuiycvdrtiqsh"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[realtime]
enabled = true

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[functions.together-ai]
verify_jwt = true

[functions.assistant-ai]
verify_jwt = true

// [functions.resume-analyzer]
// verify_jwt = true
