
project_id = "siuqvhscuiycvdrtiqsh"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[realtime]
enabled = true

[storage]
enabled = true

[auth]
enabled = true

[functions]
[functions.admin-users]
verify_jwt = true

[functions.generate-message]
verify_jwt = true

[functions.assistant-ai]
verify_jwt = true

[functions.resume-analyzer]
verify_jwt = true
