-- Seed events table with initial data
INSERT INTO events (id, title, description, type, format, location, link, date, start_time, end_time, image, capacity, calendly_link)
VALUES 
  (
    gen_random_uuid(),
    'Data Science Workshop',
    'Learn the fundamentals of data science, from data preprocessing to model deployment.',
    'workshop',
    'in-person',
    'San Francisco Tech Hub',
    NULL,
    '2025-05-15',
    '09:00',
    '17:00',
    'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTY4MTY5ODY2OA&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080',
    50,
    'https://calendly.com/insightscollective/data-science-workshop'
  ),
  (
    gen_random_uuid(),
    'Machine Learning Conference 2025',
    'Join leading experts in machine learning for talks, workshops, and networking opportunities.',
    'conference',
    'hybrid',
    'New York Convention Center',
    'https://example.com/ml-conference',
    '2025-06-10',
    '08:30',
    '18:00',
    'https://images.unsplash.com/photo-1498050108023-c5249f4df085?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTY4MTY5ODc2OQ&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080',
    300,
    'https://calendly.com/insightscollective/ml-conference'
  ),
  (
    gen_random_uuid(),
    'Python for Data Analysis Webinar',
    'Master Python libraries for data analysis including pandas, numpy, and matplotlib in this comprehensive webinar.',
    'webinar',
    'online',
    NULL,
    'https://example.com/python-webinar',
    '2025-05-20',
    '14:00',
    '16:00',
    'https://images.unsplash.com/photo-1451187580459-43490279c0fa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTY4MTY5ODg3Ng&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080',
    NULL,
    'https://calendly.com/insightscollective/python-webinar'
  ),
  (
    gen_random_uuid(),
    'AI Ethics Meetup',
    'A discussion group focused on ethical considerations in artificial intelligence development and deployment.',
    'meetup',
    'in-person',
    'Boston Innovation Hub',
    NULL,
    '2025-05-25',
    '18:00',
    '20:00',
    'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTY4MTY5ODg3Ng&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080',
    30,
    'https://calendly.com/insightscollective/ai-ethics-meetup'
  ),
  (
    gen_random_uuid(),
    'Data Visualization Summer Bootcamp',
    'Intensive 2-week bootcamp covering data visualization principles, tools, and best practices for creating impactful data stories.',
    'bootcamp',
    'hybrid',
    'Seattle Tech Campus',
    'https://example.com/dataviz-bootcamp',
    '2025-07-14',
    '09:00',
    '17:00',
    'https://images.unsplash.com/photo-1551288049-bebda4e38f71?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTY4MTY5ODc2OQ&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080',
    40,
    'https://calendly.com/insightscollective/data-visualization-bootcamp'
  ),
  (
    gen_random_uuid(),
    'Data Visualization Hackathon',
    '48-hour competition to create the most innovative and informative data visualizations from public datasets.',
    'hackathon',
    'hybrid',
    'Seattle Tech Campus',
    'https://example.com/dataviz-hackathon',
    '2025-07-15',
    '09:00',
    NULL,
    'https://images.unsplash.com/photo-1519389950473-47ba0277781c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTY4MTY5ODc2OQ&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080',
    100,
    'https://calendly.com/insightscollective/data-visualization-hackathon'
  )
ON CONFLICT (id) DO NOTHING;