
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/supabase';
import { securityConfig } from '@/config/security';

const SUPABASE_URL = securityConfig.supabase.url;
const SUPABASE_PUBLISHABLE_KEY = securityConfig.supabase.key;

// Create a single instance of the Supabase client with proper auth configuration
const supabaseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage,
    storageKey: 'supabase.auth.token',
    detectSessionInUrl: true,
    flowType: 'implicit'
  }
});

// Export a singleton instance to prevent multiple client creations
export const supabase = supabaseClient;
